### ISSUE TITLE
git clone --recursive error

### ISSUE THREAD

**Issue by dmitris** [madwyn/pbrpc#1]
I assume the code should be checked out with:

```
git clone --recursive git@github.com:madwyn/pbrpc.git
```

(Maybe it would be worth to add explicitly in the README?)

I'm getting an error with deps/mongoose:

```
Cloning into 'deps/mongoose'...
remote: Counting objects: 6364, done.
remote: Total 6364 (delta 0), reused 0 (delta 0), pack-reused 6364
Receiving objects: 100% (6364/6364), 7.18 MiB | 381.00 KiB/s, done.
Resolving deltas: 100% (3571/3571), done.
Checking connectivity... done.
fatal: reference is not a tree: 7d236d7f33f522dcb951d799b7c7a2ef1f8e8469
Unable to checkout '7d236d7f33f522dcb951d799b7c7a2ef1f8e8469' in submodule path 'deps/mongoose'
```

 deps/mongoose directory remains empty (unlike deps/libpbrpc/ which does have files).

Do you know why it happens and how to fix it?  Thanks!

**Comment by madwyn** [comment]
Thank you for reporting this. I just did a quick test, it is really broken.

I will try to fix it soon.

**Comment by madwyn** [comment]
It should be working now, sorry for the trouble.
