### ISSUE TITLE
Cannot build the project, CMakeLists.txt not found in deps

### ISSUE THREAD

**Issue by sajanshakya129** [madwyn/pbrpc#2]
I m taking this project as a reference to build a RPC. I forked the project. But could not build the project.. It seems there is no CMakeLists.txt file in deps folderm So I created it.
`cmake_minimum_required(VERSION 2.8.4)

add_subdirectory(libpbrpc)
add_subdirectory(mongoose)`

it worked but i got another error.
`MONGOOSE_ROOT_DIR must be set to the location of mongoose sources.`
Can you help me out.. i m not quite much familier with how Cmake works in the mongoose directory (i noticed that you have forked it from casenta and created own CMakeLists file for it'

Thanks for help

**Comment by madwyn** [comment]
Hi, you will need to use git to pull all the submodules first.

Apart from this, I'm no longer maintaining this repository as google has released their own version of pbrpc, which is grpc.

There is a major limitation for pbrpc which is it doesn't support async.

I would recommend to check out grpc instead.

**Comment by sajanshakya129** [comment]
actually i m creating a RPC over CoAP protocol, I have forked your library
as it was easier to understand than GRPC, Right now i m trying to implement
Client part which you didnt have on prbc example..Anyways thanks for
replying. :)
